#!/usr/bin/env php
<?php

// bin/directive
declare(strict_types=1);

// Trouver l'autoloader
$autoloadPaths = [
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
    getcwd() . '/vendor/autoload.php',
];

$autoloadFound = false;
foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require_once $path;
        $autoloadFound = true;
        break;
    }
}

if (!$autoloadFound) {
    fwrite(STDERR, "ERROR: Autoloader not found. Run 'composer install' first.\n");
    exit(1);
}

use AndyDefer\Directive\Collections\TypedRecords;
use AndyDefer\Directive\Config\DirectiveConfig;
use AndyDefer\Directive\DirectiveKernel;
use AndyDefer\Directive\Factories\ContainerDirectiveFactory;
use AndyDefer\Directive\Records\DirectiveExecutionRecord;
use AndyDefer\Directive\Services\DirectiveDiscoveryService;
use AndyDefer\Directive\Services\DirectiveExecutionService;
use AndyDefer\Directive\Services\DirectiveHydratorService;
use AndyDefer\Directive\Services\DirectiveParserService;
use AndyDefer\Directive\Services\DirectiveRendererService;
use AndyDefer\Directive\Tasks\AskQuestionTask;
use AndyDefer\Directive\Tasks\ConfirmQuestionTask;
use AndyDefer\Directive\Tasks\DisplayErrorTask;
use AndyDefer\Directive\Tasks\DisplayMessageTask;
use AndyDefer\Directive\Tasks\DisplayTableTask;
use Illuminate\Container\Container;

$container = new Container();

$container->singleton(DisplayMessageTask::class);
$container->singleton(AskQuestionTask::class);
$container->singleton(ConfirmQuestionTask::class);
$container->singleton(DisplayTableTask::class);
$container->singleton(DisplayErrorTask::class);

$projectRoot = getcwd();
$directivesPath = $projectRoot . '/app/Directives';

if (file_exists($projectRoot . '/config/directive.php')) {
    $config = require $projectRoot . '/config/directive.php';
    $directivesPath = $config['path'] ?? $directivesPath;
}

$directiveConfig = DirectiveConfig::default()->withDirectivesPath($directivesPath);

$factory = new ContainerDirectiveFactory($container);
$parser = new DirectiveParserService();
$hydrator = new DirectiveHydratorService($factory);
$discovery = new DirectiveDiscoveryService($directiveConfig, $hydrator);
$renderer = new DirectiveRendererService();
$displayMessage = $container->make(DisplayMessageTask::class);
$displayError = $container->make(DisplayErrorTask::class);

$executionService = new DirectiveExecutionService(
    $discovery,
    $parser,
    $hydrator,
    $renderer,
    $displayMessage,
    $displayError,
    null,
);

$kernel = new DirectiveKernel($executionService);
$exitCode = $kernel->run($argv);

exit($exitCode->value);
